server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: false


logging:
  level:
    com.ecommerce: DEBUG
  domain:
    name: http://localhost:8081

swagger:
  host:
    url: http://localhost:8081

data:
  max-records: 99