server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: false


logging:
  level:
    com.direct24a: DEBUG
  domain:
    name: http://localhost:8081

swagger:
  host:
    url: http://localhost:8081

apiService:
  url: https://wiremock.dev.eroninternational.com/api/movies/search
  readTimeoutMillis: 5000
  connectionTimeoutMillis: 10000


